### PR TITLE
Added Open API spec in both json and yaml formats

### PR DESCRIPTION
**Pull request by ssjiang**

### CODE REVIEW

**Comment by ssjiang** [comment]
Added a new endpoint and created both json and yaml files.

**Comment by semihyumusak** [comment]
approve

**Comment by semihyumusak** [comment]
@ssjiang As I merged the previous pull request. this pull request created a conflict. Could you please resolve them?

**Comment by ssjiang** [comment]
@semihyumusak I have resolved the conflicts. You can approve and merge them to the main branch now

**Pull request merged**
